<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>mlog</string>
	</array>
	<key>name</key>
	<string>Mlog</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(((f|F)ixed).\s*)</string>
			<key>name</key>
			<string>meta.fixed.mlog</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(((d|D)elay).\s*)</string>
			<key>name</key>
			<string>meta.delay.mlog</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(((r|R)efused).\s*)</string>
			<key>name</key>
			<string>meta.refused.mlog</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\*\*\s*TODO\s*</string>
			<key>name</key>
			<string>meta.todo.mlog</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\*\*\s*NEXT\s*</string>
			<key>name</key>
			<string>meta.next.mlog</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\*\*\s*WORK\s*</string>
			<key>name</key>
			<string>meta.work.mlog</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\*\*\s*DONE\s*</string>
			<key>name</key>
			<string>meta.done.mlog</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\s*((//).*$
?)</string>
			<key>name</key>
			<string>meta.comment.mlog</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>meta.comment.mlog</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.mlog</string>
	<key>uuid</key>
	<string>f9bd1645-6dab-48b8-ae3d-5a30437f1316</string>
</dict>
</plist>
