<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>mlog</string>
	</array>
	<key>name</key>
	<string>Mlog</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(((f|F)ixed).\s*)</string>
			<key>name</key>
			<string>meta.fixed.mlog</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(((d|D)elay).\s*)</string>
			<key>name</key>
			<string>meta.delay.mlog</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(((r|R)efused).\s*)</string>
			<key>name</key>
			<string>meta.refused.mlog</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\*\*\s*TODO\s*</string>
			<key>name</key>
			<string>meta.todo.mlog</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\*\*\s*NEXT\s*</string>
			<key>name</key>
			<string>meta.next.mlog</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\*\*\s*WORK\s*</string>
			<key>name</key>
			<string>meta.work.mlog</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\*\*\s*DONE\s*</string>
			<key>name</key>
			<string>meta.done.mlog</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\s*((//).*$
?)</string>
			<key>name</key>
			<string>meta.comment.mlog</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>meta.comment.mlog</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\s*(\@)</string>
			<key>end</key>
			<string>\s</string>
			<key>name</key>
			<string>meta.username.mlog</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\s*(\#(10|INVERSE)).*$
?)</string>
			<key>name</key>
			<string>meta.level10.mlog</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\s*(\#(9|ERROR)).*$
?)</string>
			<key>name</key>
			<string>meta.level9.mlog</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\s*(\#(8|INFO)).*$
?)</string>
			<key>name</key>
			<string>meta.level8.mlog</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\s*(\#7).*$
?)</string>
			<key>name</key>
			<string>meta.level7.mlog</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\s*(\#(6|IMPORTANT)).*$
?)</string>
			<key>name</key>
			<string>meta.level6.mlog</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\s*(\#5).*$
?)</string>
			<key>name</key>
			<string>meta.level5.mlog</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\s*(\#(4|WARNING)).*$
?)</string>
			<key>name</key>
			<string>meta.level4.mlog</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\s*(\#3).*$
?)</string>
			<key>name</key>
			<string>meta.level3.mlog</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\s*(\#(2|SUCCESS)).*$
?)</string>
			<key>name</key>
			<string>meta.level2.mlog</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\s*(\#\d).*$
?)|(\s*(\#DEFAULT).*$
?)</string>
			<key>name</key>
			<string>meta.level1.mlog</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.mlog</string>
	<key>uuid</key>
	<string>f9bd1645-6dab-48b8-ae3d-5a30437f1316</string>
</dict>
</plist>
